name: Delete old workflow runs
#on:
#  schedule:
#    - cron: '0 0 * * *'  # Runs every day at midnight
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    name: A demo job to delete workflow runs
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete workflow runs
        id: delete-old-workflow-runs
        # You may pin to the exact commit or the version.
        # uses: Mattraks/delete-workflow-runs@39f0bbed25d76b34de5594dceab824811479e5de
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          # Authentication token
          #token: # default is ${{ github.token }}
          # Base API URL
          #baseUrl: # optional, default is https://api.github.com
          # Name of the repository
          #repository: # default is ${{ github.repository }}
          # Days-worth of runs to keep for each workflow
          retain_days: 1 # default is 30
          # Minimum runs to keep for each workflow
          #keep_minimum_runs: # default is 6
          # Name or filename of the workflow (if not set, all workflows are targeted)
          #delete_workflow_pattern: # optional
          # Filter workflows by state: active, deleted, disabled_fork, disabled_inactivity, disabled_manually
          #delete_workflow_by_state_pattern: # optional
          # Remove runs based on conclusion: action_required, cancelled, failure, skipped, success
          #delete_run_by_conclusion_pattern: # optional
          # Logs simulated changes, no deletions are performed
          #dry_run: # optional
          # If the workflow was triggered by a branch, the branch must be deleted before the workflow run is deleted as well.
          #check_branch_existence: # optional
          # If the run is linked to a pull request, the deletion is skipped.
          #check_pullrequest_exist: # optional
          
