name: Delete old workflow runs
#on:
#  schedule:
#    - cron: '0 0 * * *'  # Runs every day at midnight
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      minimumRunsToKeep:
        description: 'Number of workflow runs to keep'
        required: true
        default: '10'
      workflowName:
        description: 'Name of workflow to delete from'
        required: true
        default: 'Builds'

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    name: A demo job to delete workflow runs
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete workflow runs
        id: delete-old-workflow-runs
        uses: mwigginsdev/delete-oldest-workflow-runs@main
        with:
          token: ${{ secrets.AUTH_PAT }}
          repository: ${{ github.repository }}
          keep_minimum_runs: ${{ github.event.inputs.minimumRunsToKeep }}
          workflow_name: ${{ github.event.inputs.workflowName }}
          #check_pullrequest_exist: # optional
          
