name: Delete old workflow runs
#on:
#  schedule:
#    - cron: '0 0 * * *'  # Runs every day at midnight

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old runs
        uses: marketplace/actions/delete-workflow-runs@v2.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
